# Generated by Django 4.2.7 on 2023-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=250)),
                ('Nation', models.CharField(max_length=250)),
                ('Team', models.CharField(max_length=250)),
                ('PlayerName', models.CharField(max_length=250)),
            ],
        ),
    ]
